# Generated by Django 3.2.8 on 2021-10-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211016_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editpage',
            name='profileimg',
            field=models.ImageField(upload_to='pics/'),
        ),
    ]
