# Generated by Django 3.2.8 on 2021-10-18 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_alter_editpage_profileimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileimg', models.ImageField(blank=True, default='default.png', null=True, upload_to='pics/')),
                ('bio', models.TextField()),
                ('country', models.CharField(max_length=30)),
                ('website', models.CharField(max_length=200)),
                ('istagram', models.CharField(max_length=200)),
                ('facebook', models.CharField(max_length=200)),
                ('linkedin', models.CharField(max_length=200)),
                ('twitter', models.CharField(max_length=200)),
                ('user1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='editpage',
        ),
    ]
