# Generated by Django 3.0.3 on 2021-10-23 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=255)),
                ('websiteURL', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('zipcode', models.CharField(blank=True, max_length=255)),
                ('campaignName', models.CharField(blank=True, max_length=255)),
                ('campaignTagline', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('startdate', models.DateField(blank=True)),
                ('enddate', models.DateField(blank=True)),
                ('pitchCampaignName', models.CharField(blank=True, max_length=255)),
                ('pitchFile', models.FileField(blank=True, null=True, upload_to='files/')),
                ('vidlink', models.CharField(blank=True, max_length=255)),
                ('campaignPitch', models.CharField(blank=True, max_length=255)),
                ('campaignGoal', models.CharField(blank=True, max_length=255)),
                ('price', models.IntegerField(blank=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('rewardfile', models.FileField(blank=True, null=True, upload_to='files/')),
                ('shippingInfo', models.TextField(blank=True)),
                ('deliveryTime', models.DateField(blank=True)),
                ('faqs', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
