# Generated by Django 3.0.3 on 2021-10-23 22:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='enddate',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 23, 22, 30, 42, 585136, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='startdate',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 23, 22, 30, 42, 585136, tzinfo=utc)),
        ),
    ]
