# Generated by Django 3.0.3 on 2021-10-23 22:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211024_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='enddate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='startdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
