# Generated by Django 3.0.3 on 2021-10-23 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211024_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
