# Generated by Django 3.0.3 on 2021-10-23 22:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211024_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='deliveryTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
