# Generated by Django 3.0.3 on 2021-10-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211024_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='rewarddetails',
            field=models.TextField(blank=True),
        ),
    ]
