# Generated by Django 3.0.3 on 2021-10-26 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_campaign_rewarddetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_complete',
            field=models.BooleanField(default=True),
        ),
    ]
